name: bob
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - pip
  - pip:
    - numpy==1.26.4
    - pydantic==1.10.11
    - meerkat-ml
    - jupyterlab
    - pybioclip
    - polars
